version: '3'

tasks:
  compile:
    desc: "Compile markdown files to HTML"
    cmds:
      - | 
        find posts -type f -name "*.md" -exec sh -c \
          'pandoc --template assets/templates/post.html \
            --toc --toc-depth=1 \
            --citeproc \
            -o "${0%.md}.html" "$0"' \
          {} \;
