version: '3'

tasks:
  compile:
    desc: "Compile markdown files to HTML"
    cmds:
      - | 
        find posts -type f -name "*.md" -exec sh -c \
          'pandoc --template assets/templates/post.html \
            --toc --toc-depth=1 \
            --citeproc \
            -o "${0%.md}.html" "$0"' \
          {} \;
  nuke:
    desc: "Delete anything that isn't HTML"
    prompt: "Don't run this unless you've comitted your changes. Are you sure?"
    cmds:
      - find posts -type f ! -name "*.html" -delete
  clean:
    desc: "Delete compiled HTML files"
    cmds:
      - find posts -type f -name "*.html" -not -name "_index.html" -delete

