name: CI
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # Define a job to generate the site content
  # * Uses pandoc to convert markdown to HTML
  # * Bundles site into zipped artifact
  generate-site:
    runs-on: ubuntu-latest
    container: 
      image: pandoc/core:latest-ubuntu
      options: --entrypoint=sh  

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Convert any markdown files in the content folder to HTML
      # * Deletes the markdown afterwards
      - name: Convert markdown to HTML
        run: |
          find posts -type f -name "*.md" -exec sh -c \
            'pandoc --template assets/templates/post.html \
              --toc --toc-depth=1 \
              -o "${0%.md}.html" "$0"; \
              rm "$0";' \
            {} \;
      - name: Setup Pages
        uses: actions/configure-pages@v3
      # Upload the entire repository as the site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
        
  # Define a job to deploy the static files
  deploy:
    runs-on: ubuntu-latest
    needs: generate-site
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
